# -------------------- MONGO --------------------
apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  containers:
    - name: mongo
      image: mongo:7
      ports:
        - containerPort: 27017
      volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
  volumes:
    - name: mongo-storage
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017

# -------------------- AGON --------------------
---
apiVersion: v1
kind: Pod
metadata:
  name: agon
  labels:
    app: agon
spec:
  containers:
    - name: agon
      image: abhidev333/agon:latest
      ports:
        - containerPort: 8000
      env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONDONTWRITEBYTECODE
          value: "1"
        - name: GOOGLE_API_KEY
          value: "YOUR_GOOGLE_API_KEY"
---
apiVersion: v1
kind: Service
metadata:
  name: agon
spec:
  selector:
    app: agon
  ports:
    - port: 8000
      targetPort: 8000

# -------------------- BACKEND --------------------
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend
spec:
  containers:
    - name: backend
      image: abhidev333/backend:latest
      ports:
        - containerPort: 4000
      env:
        - name: PORT
          value: "4000"
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/ai-app"
        - name: ACCESS_TOKEN_SECRET
          value: "replace_with_strong_random_secret"
        - name: REFRESH_TOKEN_SECRET
          value: "replace_with_another_secret"
        - name: ACCESS_TOKEN_EXPIRES_IN
          value: "15m"
        - name: REFRESH_TOKEN_EXPIRES_IN
          value: "7d"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 4000
      targetPort: 4000

# -------------------- FRONTEND --------------------
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
    - name: frontend
      image: abhidev333/frontend:latest
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007

# -------------------- PROMETHEUS --------------------
---
apiVersion: v1
kind: Pod
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  containers:
    - name: prometheus
      image: prom/prometheus:latest
      args:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus"
        - "--storage.tsdb.retention.time=30d"
        - "--web.enable-lifecycle"
      ports:
        - containerPort: 9090
      volumeMounts:
        - name: prom-config
          mountPath: /etc/prometheus
        - name: prom-storage
          mountPath: /prometheus
  volumes:
    - name: prom-config
      hostPath:
        path: /home/abhi/prometheus.yml # change if needed
    - name: prom-storage
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090

# -------------------- GRAFANA --------------------
---
apiVersion: v1
kind: Pod
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  containers:
    - name: grafana
      image: grafana/grafana:latest
      ports:
        - containerPort: 3000
      env:
        - name: GF_SECURITY_ADMIN_USER
          value: "admin"
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"
        - name: GF_USERS_ALLOW_SIGN_UP
          value: "false"
      volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
  volumes:
    - name: grafana-storage
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
